version: '3.3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.3.1
    user: root
    command: --strict.perms=false
    environment:
      - OUTPUT_ELASTICSEARCH_HOSTS=["elasticsearch:9200"]
    volumes:
      - "/var/data/filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/data:/var/data"
      - "/var/data/filebeat/modules.d:/usr/share/filebeat/modules.d"
    networks:
      - elk
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

networks:
  elk:
    external: true
      