version: '3.3'
services:
  server:
    image: consul
    command: agent -server -client=0.0.0.0 -bootstrap-expect=1 -ui
    volumes:
      - /var/data/consul-leader:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"datacenter":"home","server":true,"leave_on_terminate": true}'
    networks:
      traefik_public: 
      consul:
        aliases:
          - consul.cluster
    command: agent -ui -data-dir /consul/data -server -client 0.0.0.0 -bootstrap-expect=1 -retry-join consul.cluster
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.frontend.rule=Host:consul.york.haus
        - traefik.enable=true
        - traefik.port=8500
        - traefik.tags=traefik_public
        - traefik.docker.network=traefik_public
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
  client:
    image: consul
    command: agent -server -client=0.0.0.0 -retry-join="consul-leader"
    volumes:
      - /var/data/consul-client:/consul/data
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "datacenter": "home", "data_dir":"/consul/data"}'
    command: agent -ui -data-dir /consul/data -client 0.0.0.0 -retry-join consul.cluster 
    networks:
      consul:
        aliases:
          - consul.client.cluster
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints: [node.role == manager]
  traefik:
    image: traefik:1.7
    environment:
      - GCE_PROJECT=yorkhaus-223621
      - GCE_SERVICE_ACCOUNT_FILE=/google.json
      - TZ=US/Chicago
      - PUID=988
      - PGID=1001
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      restart_policy: 
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.york.haus
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=traefik_public
        - traefik.docker.network=traefik_public
        # Traefik service that listens to HTTP
        #- traefik.redirectorservice.frontend.entryPoints=http
        #- traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        #- traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/data/traefik/traefik.log:/var/log/traefik.log
      - /var/data/traefik/acme/acme.json:/acme.json
      - /var/data/traefik/acme/yorkhaus-223621-7a7e90aee291.json:/google.json
    command: 
      - "--consul"
      - "--consul.endpoint=consul.cluster:8500"
      - "--consul.prefix=traefik"
    networks:
      - consul
      - traefik_public
    depends_on:
      - server
      - traefik_init
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    env_file: /var/data/traefik/traefik-forward-auth.env
    command:
      - "--auth-host=auth.york.haus"
      - "--cookie-domain=york.haus"
      - "--log-level=debug"
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=4181
        - traefik.frontend.rule=Host:auth.york.haus
        - traefik.backend=traefik-forward-auth
        - traefik.frontend.auth.forward.trustForwardHeader=true
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders = ["X-Forwarded-User"]
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost="
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
  traefik_init:
    image: traefik:1.7
    volumes: 
      - /var/data/traefik/acme/acme.json:/acme.json
      - /var/data/traefik/acme/yorkhaus-223621-7a7e90aee291.json:/google.json
    environment:
      - GCE_PROJECT=yorkhaus-223621
      - GCE_SERVICE_ACCOUNT_FILE=/google.json
      - TZ=US/Chicago
      - PUID=988
      - PGID=1001
    command:
      - "storeconfig"
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.overridecertificates=true"
      - "--acme.email=syork@yorkserv.com"
      - "--acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--acme.domains=*.york.haus,york.haus"
      - "--acme.domains=*.yorkserv.com,yorkserv.com"
      - "--acme.onDemand=false"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge.provider=gcloud"
      - "--acme.onhostrule=true"
      - "--acme.acmelogging=true"
      - "--logLevel=DEBUG"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=york.haus"
      - "--docker.watch"
      - "--consul"
      - "--consul.endpoint=consul.cluster:8500"
      - "--consul.prefix=traefik"
      - "--traefiklog.filePath=/var/log/traefik.log"
      - "--traefiklog.format=common"
    networks:
      - consul
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - server
secrets:
  gce_service_account_file:
    external: true
networks:
  consul:
    external: true
  traefik:
    external: true
  traefik_public:
    external: true