version: '3.7'

services:
  server:
    image: consul:1.6.3
    command: "agent -config-dir /consul/config -data-dir /consul/data -bootstrap-expect 3 -client 0.0.0.0"
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'
    networks:
      - macvlan_swarm
      - consul
    ports:
      - 8500:8500
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        failure_action: pause
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    volumes:
       - consul:/consul 

  consul-agent:
    image: consul:1.6.3
    volumes:
      - consul:/consul
    command: "agent -client 0.0.0.0  -config-file /consul/config/consul.hcl"
    deploy:
      mode: global
    depends_on:
      - server
    networks:
      - consul
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'

networks:
  appnet:
    external: true
  macvlan_swarm:
    external: true
  consul:
    driver: overlay
    attachable: true
volumes:
  consul:
    external: true
