version: "3.6"
services:
  vault:
  image: vault
  networks:
    - consul 
  ports:
    - 8200:8200
  volumes:
    - vault/config/:/vault/config
    - vault/polices:/vault/polices
    - vault/data:/vault/data
    - vault/logs:/vault/logs
  environment:
    - VAULT_ADDR=http://127://127.0.0.1:8200
  command: server -config=/vault/config/vault-config.json
  cap_cadd:
    - IPC_LOCK

networks:
  consul:
    external: true
volumes:
  consul:
    external: true
  vault:
    exteranl: true
