version: "3.7"
services:
  vault:
    image: vault
    networks:
      - macvlan_swarm
      - consul_consul
    ports:
      - 8200:8200
    volumes:
      - vault:/vault
    command: "server -config=/vault/config/vault-config.json"
    environment:
      - VAULT_CONFIG=/vault/config/vault-config.json
    deploy:
      resources:
        reservations:
          cpus: '.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        order: stop-first

networks:
  macvlan_swarm:
    external: true
  consul_consul:
    external: true
volumes:
  vault:
    external: true
