version: "3.2"
services:
  mongo:
    image: mongo:3.4
    deploy:
      replicas: 1
    volumes:
        - /var/data/mongo:/data/db
        - /etc/localtime:/etc/localtime:ro
    ports:
        - 27017:27017
    networks: 
      - default
    environment:
        PUID: 988
        PGID: 1001
        TZ: America/Chicago
  mongo-express:
    image: mongo-express
    networks:
      - default
    deploy:
     replicas: 1
     labels:
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

networks:
  unifi_internal: 
    external: true

